version: '3'

services:
  mysql:
    container_name: mysql
    image: gr-db
    environment:
      MYSQL_DATABASE: gr-db
      MYSQL_ROOT_PASSWORD: root-1234
    ports:
      - "3306:3306"
      - "8084:3306"
